spring.application.name=Task Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=Prueba1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=m3RZ5D3T1A8oX6z0n0ZP+9Z9QzPz0v7kZ8k=
jwt.expiration=86400000